### ISSUE TITLE
Does this example use ajax / superagent? 

### ISSUE THREAD

**Issue by dukedougal** [gcanti/tcomb-spa-example#1]
The documentation / requirements mentions both ajax and superagent but I can't see in the code where the ajax is done and I can't see network requests being sent during usage of the app.

**Comment by gcanti** [comment]
Hi, 
you are right, currently the ajax calls are fake (in the https://github.com/gcanti/tcomb-spa-example/blob/master/src/Server.js file)

**Comment by dukedougal** [comment]
Would you be willing to suggest to me the key things I would need to do if I wanted to hook this up to a real server using superagent? thanks

**Comment by gcanti** [comment]
I think you should just replace my fake calls using setTimeout with real superagent calls:

https://github.com/gcanti/tcomb-spa-example/blob/master/src/Server.js#L18-L23

**Comment by dukedougal** [comment]
Please forgive my beginner questions - I am learning react and npm.

I am making the changes you suggest in the code but it does not appear to be executing.  

Do I need to do some sort of build process or something to see my changes?

Also is there some way I can build this code into standalone code that I can run on my nginx web server?

thanks heaps.
