### ISSUE TITLE
build error decorators

### ISSUE THREAD

**Issue by mvayngrib** [gcanti/tcomb-spa-example#16]
@gcanti first, love your tcomb libraries!

after running `npm run watch` I get a bunch of these errors: 

```bash
ERROR in ./src/api/index.js
Module build failed: SyntaxError: /Users/tenaciousmv/Code/tcomb-spa-example/src/api/index.js: Unexpected token (1:20)
> 1 | export default from './memory'
...
ERROR in ./src/routes/SignInRoute.js
Module build failed: SyntaxError: /Users/tenaciousmv/Code/tcomb-spa-example/src/routes/SignInRoute.js: Unexpected token (6:0)
  4 | import SignInPage from '../components/SignInPage'
  5 | 
> 6 | @props({
```

have you run into this?

**Comment by gcanti** [comment]
Hi @mvayngrib,

I'm sorry, the master branch is quite a mess at the moment. I'm refactoring the whole app using this new library https://github.com/gcanti/tom of mine.
I have a local branch with a lot of changes, hope to push a stable version asap.

**Comment by mvayngrib** [comment]
@gcanti awesome, will be on the lookout
