### ISSUE TITLE
Question regarding datatable to use with tcomb-form

### ISSUE THREAD

**Issue by dukedougal** [gcanti/tcomb-spa-example#2]
Hello I am using tcomb-form and your spa-example application and I Like them both very much - well done.

I want to ask your advice.  I wish to display a datatable, which the user can then select row using a checkbox or something similar, and then submit to the back end which ones have been checked.

Are you able to suggest or recommend a way of approaching this that would work well with your tcomb stuff?

thanks

**Comment by gcanti** [comment]
Hi,
If you find a suitable table implementation you could write a custom component.
This is a quick (and incomplete!) example, just to give you an idea 
(react-table-select is just the first result searching "table react selectable")

```js
// watchify -t [reactify --harmony] dev/dev.jsx -o dev/dev.js -v -x react

'use strict';

var React = require('react');
var t = require('tcomb-form');
var TableSelect = require('react-table-select');

var Form = t.form.Form;

// your custom component
class MyComponent extends t.form.Component {

  render() {
    const locals = this.getLocals();
    return (
      <TableSelect
        className="table"
        data={locals.config.data}
        onChange={locals.onChange}
      />
    );
  }

}

var Type = t.struct({
  name: t.Str,
  mylist: t.list(t.Num) // <- maybe in your case will be t.list(t.Str). It's t.list(t.Num) due to the internals of react-table-select...
});

var options = {
  fields: {
    mylist: {
      config: { // <-- pass here your custom options
        data: [{one: 'fish'}, {two: 'fish'}, {red: 'fish'}, {blue: 'fish'}]
      },
      factory: MyComponent // <- override the default input component
    }
  }
};

var value = {
  mylist: [] // <-- set a default value for the list
};

var App = React.createClass({

  onSubmit(evt) {
    evt.preventDefault();
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render() {
    return (
      <form onSubmit={this.onSubmit}>
        <Form ref="form"
          type={Type}
          options={options}
          value={value}
        />
        <button className="btn btn-primary">Save</button>
      </form>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by dukedougal** [comment]
Hello Giulio

I'm sorry to be such a newbie but I've spent the past two days trying to get this to work as a page within your single page application

I am aiming to put checkboxes on your products list and buttons to add and delete new products.

I'm really stuck - I can't get past this message in the console saying: "Uncaught TypeError: inst.render is not a function"

Any help appreciated - again sorry to be such a newb but I'm learning this stuff. If you can show a little more about how to add checkboxes and add/delete buttons for the products in your SPA that would be awesome.

thanks

**Comment by dukedougal** [comment]
Hi there
I am sorry after trying for days to make this work I have had to give up.
I am wondering if it would be easier to add checkboxes to your purchases list in the SPA? Again might I trouble you to suggest the most effective way to do this? Sorry to be asking so much help but I'm giving this a real good go and not winning.....
thanks heaps.
