### ISSUE TITLE
304 errors after npm start

### ISSUE THREAD

**Issue by dukedougal** [gcanti/tcomb-spa-example#8]
PS C:\Users\username\devel\tcomb-spa-example> npm start
 
> tcomb-spa-example@0.5.0 start C:\Users\username\devel\tcomb-spa-example
> nodemon -w server server/app
 
6 Nov 16:43:59 - [nodemon] v1.4.1
6 Nov 16:43:59 - [nodemon] to restart at any time, enter `rs`
6 Nov 16:43:59 - [nodemon] watching: C:\Users\username\devel\tcomb-spa-example\server/**/*
6 Nov 16:43:59 - [nodemon] starting `node server/app index.js`
[INFO] Server listening on port 4002
[INFO] Open http://localhost:4002/bootstrap in your browser

Here is what displays in the Chrome network panel:

bootstrap       304     document        Other   151 B 3 ms 
bootstrap.min.css       304     stylesheet      bootstrap:8     244 B 5 ms 
spa.css 304     stylesheet      bootstrap:9     242 B 5 ms 
spa.main.js     404     script  bootstrap:13    0 B   41 ms
spa.en-US.js    404     script  bootstrap:14    0 B   41 ms

**Comment by gcanti** [comment]
I guess **404** errors. You need 2 terminals:

```sh
# terminal 1
$ npm run watch # compiles the sources to the /dist folder

#terminal 2
$ npm start # starts the fake server

# then point a browser to http://localhost:4002/bootstrap
```
