### ISSUE TITLE
npm run build not working on Windows

### ISSUE THREAD

**Issue by dukedougal** [gcanti/tcomb-spa-example#9]
I wonder if this is the issue: http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman

PS C:\Users\username\devel\tcomb-spa-example> npm run build

> tcomb-spa-example@0.5.0 build C:\Users\username\devel\tcomb-spa-example
> NODE_ENV=production webpack --progress

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! tcomb-spa-example@0.5.0 build: `NODE_ENV=production webpack --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tcomb-spa-example@0.5.0 build script 'NODE_ENV=production webpack --progress'.
npm ERR! This is most likely a problem with the tcomb-spa-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --progress
npm ERR! You can get their info via:
npm ERR!     npm owner ls tcomb-spa-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\devel\tcomb-spa-example\npm-debug.log
PS C:\Users\username\devel\tcomb-spa-example>

**Comment by Theadd** [comment]
>NODE_ENV=production webpack --progress

Just change that line in `package.json` to `set NODE_ENV=production&& webpack --progress`. It works perfectly fine in windows. It's not a problem with this repo, you will have to deal with that a lot.
